permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 刘伟
  email: liuwei_sj@163.com
  link: http://blog.grantliu.com
  weibo: http://weibo.com/grantliu
  github: https://github.com/liuweisj

# 站点信息
title: 刘伟的博客 
description: 刘伟的博客
url: http://blog.grantliu.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: https://a.disquscdn.com/uploads/users/13921/7429/avatar92.jpg?1421206850
favicon: http://7u2jk9.com1.z0.glb.clouddn.com/favicon.ico

# google analytics 设置
ga:
  id: UA-58525846-1
  url: blog.grantliu.com

# disqus 设置
disqus:
  shortname: liuweisj

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
